spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: h.elcin78
    url: jdbc:postgresql://localhost:5432/e-commerce
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update